#!/bin/zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="alacritty,aliases,bashtop,bin,colorls,git,mc,mutt,nvim,spotify-tui,tmux,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
